idp-service:
  nameOverride: auth-service
  image:
    repository: idp-platform/auth-service
    tag: local
  service:
    port: 80
    targetPort: 3001
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  hpa:
    minReplicas: 1
    maxReplicas: 3
  env:
    NODE_ENV: production
    PORT: "3001"
    DB_HOST: postgres.platform.svc.cluster.local
    DB_PORT: "5432"
    DB_USERNAME: idp
    DB_NAME: idp
    DB_SCHEMA: auth
    REDIS_HOST: redis.platform.svc.cluster.local
    REDIS_PORT: "6379"
    JWT_ACCESS_TOKEN_TTL_SECONDS: "900"
    JWT_REFRESH_TOKEN_TTL_SECONDS: "604800"
    JWT_ISSUER: idp-platform
    ALLOWED_ORIGINS: "http://idp.localtest.me"
  secretData:
    DB_PASSWORD: ***REMOVED***
    JWT_SECRET: local-kind-cluster-secret-change-for-real-deployments