{{- if .Values.secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idp-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}